name: Build Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_docker:
    strategy:
      matrix:
        env:
          - ROS_DISTRO: foxy
            DOCKER_NAME: moveit2
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/ignition-edifice:${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.DOCKER_NAME }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Containter Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          build-args: ROS_DISTRO=${{ matrix.env.ROS_DISTRO }}
          pull: true
          push: true
          no-cache: false
          cache-from: type=registry,ref=${{ env.IMAGE }}
          cache-to: type=inline
          tags: ${{ env.IMAGE }}
