name: Build Docker

on:
  workflow_dispatch:
  # push:
  #  branches:
  #    - main
  # schedule:
  #  # Run every day to detect flakiness and broken dependencies
  #  - cron: '0 12 * * *'

jobs:
  build_docker:
    strategy:
      matrix:
        env:
          - ROS_DISTRO: foxy
            DOCKER_NAME: moveit2
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_ID: ghcr.io/${{ github.repository_owner }}/ignition-edifice
      VERSION: ${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.DOCKER_NAME }}

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          echo Building docker ${{ env.IMAGE_ID }}:${{ env.VERSION }}
          docker build . --build-arg ROS_DISTRO=${{ matrix.env.ROS_DISTRO }} --file Dockerfile --tag ${{ env.IMAGE_ID }}:${{ env.VERSION }}
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker push ${{ env.IMAGE_ID }}:${{ env.VERSION }}
